### ISSUE TITLE
SEO tab checklist showing undefined

### ISSUE THREAD

**Issue by glenwith1n** [tim-digitalastronaut/craft-author-toolbar#10]
After upgrading to the lat version v1.1.11-beta, the SEO tab checklist has a bunch of undefined variable not showing what has a tick or a cross.

**Comment by BramMortier** [comment]
@glenwith1n I'm currently working on a complete rewrite of the javascript behind the toolbar because alpine was causing to many issues with multiple instances. Should be solved with that update. Hoping to get it out before friday

**Comment by glenwith1n** [comment]
I upgraded to v1.2.5-beta and still not working?
Now getting a different error - 
Twig Runtime Error – [Twig\Error\RuntimeError](http://twig.sensiolabs.org/api/2.x/Twig/Error/RuntimeError.html)
Key "message" for sequence/mapping with keys "status" does not exist.

**Comment by BramMortier** [comment]
I've released v1.2.9-beta with the fix. This issue was caused by your site being in another language than en or nl so the js translations array was empty because there was no fall back to english. If you want the toolbar to be in another language than en or nl you'll have to add your own translations file.

Hope this resolves your issue!

**Comment by BramMortier** [comment]
@glenwith1n can I close this issue? Would like ur confirmation on this to make sure :)

**Comment by glenwith1n** [comment]
These issues sorted, have another small one - the button to hide warning
about production/dev environment doesn't close that section.


Cheers, Glen

[image: Walker Designs]

[image: Walker Designs] [image: Walker Designs]

Glen Adams
Senior Designer/Developer

[image: Web] 03 6341 1800 <0363411800>
[image: Web] 0400 331 899
[image: Web] ***@***.***
[image: Web] 462 Wellington St, Launceston TAS 7250
***@***.***,147.1504265,17z/data=!3m1!4b1!4m6!3m5!1s0xaa70a152a60383ed:0x27b0bf821c3927d4!8m2!3d-41.4588672!4d147.1530014!16s%2Fg%2F11c22zb6s7?entry=ttu>
[image: Web] walkerdesigns.com.au

**Comment by BramMortier** [comment]
@glenwith1n I'm gonna fix that issue soon will keep u posted

**Comment by BramMortier** [comment]
@glenwith1n This is fixed in v1.2.10-beta!
